//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMVC.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> salary { get; set; }
        public string Department { get; set; }
        public string Genders { get; set; }
        public string Date { get; set; }
    }
}
